/**
 * Schema Analyzer
 * 
 * Utility to analyze Drizzle ORM schemas and extract metadata for code generation.
 * Detects field types, relations, enums, and constraints automatically.
 */

import * as fs from 'fs';
import * as path from 'path';

// ============================================================================
// Types
// ============================================================================

export type FieldType = 'text' | 'integer' | 'real' | 'boolean' | 'timestamp' | 'enum' | 'fk' | 'unknown';

export interface SchemaField {
  name: string;
  type: FieldType;
  isRequired: boolean;
  isPrimaryKey: boolean;
  isForeignKey: boolean;
  isAutoGenerated: boolean;
  isTimestamp: boolean;
  relatedEntity?: string;
  enumValues?: string[];
  dbType: string; // raw drizzle type
}

export interface RelationInfo {
  type: 'one-to-many' | 'many-to-one' | 'many-to-many';
  field: string;
  relatedEntity: string;
  relatedField?: string;
  junctionTable?: string;
}

export interface EntitySchema {
  name: string;
  tableName: string;
  fields: SchemaField[];
  primaryKey: string;
  hasRelations: boolean;
  relations: RelationInfo[];
  hasTimestamps: boolean;
  timestampFields: string[];
  enumFields: SchemaField[];
  fkFields: SchemaField[];
}

// ============================================================================
// Field Type Detection
// ============================================================================

/**
 * Detect field type from Drizzle column definition
 */
function detectFieldType(columnDef: string): { type: FieldType; dbType: string; enumValues?: string[] } {
  const trimmed = columnDef.trim();
  
  // Check for text type
  if (trimmed.startsWith('text(')) {
    // Check if it's a FK reference
    if (trimmed.includes('.references(')) {
      return { type: 'fk', dbType: 'text' };
    }
    return { type: 'text', dbType: 'text' };
  }
  
  // Check for integer type
  if (trimmed.startsWith('integer(')) {
    // Check if it's a timestamp
    if (trimmed.includes("mode: 'timestamp'")) {
      return { type: 'timestamp', dbType: 'integer' };
    }
    return { type: 'integer', dbType: 'integer' };
  }
  
  // Check for real/numeric type
  if (trimmed.startsWith('real(')) {
    return { type: 'real', dbType: 'real' };
  }
  
  // Check for boolean
  if (trimmed.startsWith('integer(') && trimmed.includes('boolean')) {
    return { type: 'boolean', dbType: 'integer' };
  }
  
  // Check for enum
  const enumMatch = trimmed.match(/enum:\s*\[([^\]]+)\]/);
  if (enumMatch) {
    const values = enumMatch[1]
      .split(',')
      .map(v => v.trim().replace(/['"]/g, ''))
      .filter(v => v);
    return { type: 'enum', dbType: 'text', enumValues: values };
  }
  
  return { type: 'unknown', dbType: 'unknown' };
}

/**
 * Check if field is a primary key
 */
function isPrimaryKey(columnDef: string, fieldName: string): boolean {
  return columnDef.includes('.primaryKey()');
}

/**
 * Check if field is required (notNull)
 */
function isRequired(columnDef: string): boolean {
  return columnDef.includes('.notNull()');
}

/**
 * Check if field is auto-generated
 */
function isAutoGenerated(columnDef: string): boolean {
  return columnDef.includes('$defaultFn(') || columnDef.includes('$onUpdateFn(');
}

/**
 * Check if field is a timestamp
 */
function isTimestamp(columnDef: string): boolean {
  return columnDef.includes("mode: 'timestamp'") || 
         (columnDef.includes('created_at') || columnDef.includes('updated_at'));
}

/**
 * Extract related entity from FK reference
 */
function extractRelatedEntity(columnDef: string): string | undefined {
  const match = columnDef.match(/\.references\(\s*\(\)\s*=>\s*(\w+)\./);
  if (match) {
    return match[1];
  }
  return undefined;
}

// ============================================================================
// Schema Parsing
// ============================================================================

/**
 * Parse a Drizzle schema file and extract entity metadata
 */
export function analyzeSchema(schemaPath: string, entityName: string): EntitySchema {
  const content = fs.readFileSync(schemaPath, 'utf-8');
  
  // Find the table definition
  const tableRegex = new RegExp(
    `export\\s+const\\s+${entityName}\\s*=\\s*sqliteTable\\s*\\(\\s*['"]([^'"]+)['"]\\s*,\\s*\\{([^}]+)\\}`,
    's'
  );
  
  const tableMatch = content.match(tableRegex);
  if (!tableMatch) {
    throw new Error(`Could not find table definition for ${entityName} in ${schemaPath}`);
  }
  
  const tableName = tableMatch[1];
  const fieldsBlock = tableMatch[2];
  
  // Parse individual fields
  const fields: SchemaField[] = [];
  const timestampFields: string[] = [];
  const enumFields: SchemaField[] = [];
  const fkFields: SchemaField[] = [];
  let primaryKey = 'id';
  
  // Match field definitions: fieldName: columnType(...).modifiers()
  const fieldRegex = /(\w+)\s*:\s*([^,\n]+(?:\([^)]*\)[^,\n]*)*)/g;
  let fieldMatch;
  
  while ((fieldMatch = fieldRegex.exec(fieldsBlock)) !== null) {
    const fieldName = fieldMatch[1];
    const columnDef = fieldMatch[2].trim();
    
    // Skip if it's not a column definition
    if (!columnDef.match(/^(text|integer|real|blob|numeric)\s*\(/)) {
      continue;
    }
    
    const { type, dbType, enumValues } = detectFieldType(columnDef);
    const field: SchemaField = {
      name: fieldName,
      type,
      dbType,
      isRequired: isRequired(columnDef),
      isPrimaryKey: isPrimaryKey(columnDef, fieldName),
      isForeignKey: type === 'fk',
      isAutoGenerated: isAutoGenerated(columnDef),
      isTimestamp: type === 'timestamp',
      enumValues,
      relatedEntity: extractRelatedEntity(columnDef),
    };
    
    fields.push(field);
    
    if (field.isPrimaryKey) {
      primaryKey = fieldName;
    }
    
    if (field.isTimestamp) {
      timestampFields.push(fieldName);
    }
    
    if (field.type === 'enum') {
      enumFields.push(field);
    }
    
    if (field.type === 'fk') {
      fkFields.push(field);
    }
  }
  
  // Parse relations from index.ts if it exists
  const relations = parseRelations(content, entityName);
  
  return {
    name: entityName,
    tableName,
    fields,
    primaryKey,
    hasRelations: relations.length > 0 || fkFields.length > 0,
    relations,
    hasTimestamps: timestampFields.length > 0,
    timestampFields,
    enumFields,
    fkFields,
  };
}

/**
 * Parse relations from the schema content
 */
function parseRelations(content: string, entityName: string): RelationInfo[] {
  const relations: RelationInfo[] = [];
  
  // Look for relations definition
  const relationsRegex = new RegExp(
    `export\\s+const\\s+${entityName}Relations\\s*=\\s*relations\\s*\\(\\s*${entityName}\\s*,\\s*\\(\\s*\\{\\s*(one|many)\\s*\\}\\s*\\)\\s*=>\\s*\\(\\s*\\{([^}]+)\\}`,
    's'
  );
  
  const relationsMatch = content.match(relationsRegex);
  if (relationsMatch) {
    const relationsBlock = relationsMatch[2];
    
    // Match relation definitions
    const relationRegex = /(\w+)\s*:\s*(one|many)\s*\(\s*(\w+)\s*,/g;
    let relationMatch;
    
    while ((relationMatch = relationRegex.exec(relationsBlock)) !== null) {
      const fieldName = relationMatch[1];
      const relationType = relationMatch[2] as 'one' | 'many';
      const relatedEntity = relationMatch[3];
      
      relations.push({
        type: relationType === 'one' ? 'many-to-one' : 'one-to-many',
        field: fieldName,
        relatedEntity,
      });
    }
  }
  
  return relations;
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Convert entity name to PascalCase for types
 */
export function toPascalCase(str: string): string {
  return str
    .replace(/[-_]/g, ' ')
    .replace(/(?:^\w|[A-Z]|\b\w)/g, (word) => word.toUpperCase())
    .replace(/\s+/g, '');
}

/**
 * Convert entity name to camelCase for variables
 */
export function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Get the TypeScript type for a schema field
 */
export function getTypeScriptType(field: SchemaField): string {
  switch (field.type) {
    case 'text':
    case 'enum':
    case 'fk':
      return 'string';
    case 'integer':
      return 'number';
    case 'real':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'timestamp':
      return 'Date';
    default:
      return 'unknown';
  }
}

/**
 * Get editable fields (exclude auto-generated and timestamps)
 */
export function getEditableFields(schema: EntitySchema): SchemaField[] {
  return schema.fields.filter(f => 
    !f.isAutoGenerated && 
    !f.isTimestamp &&
    !f.isPrimaryKey
  );
}

/**
 * Get visible fields (for table columns)
 */
export function getVisibleFields(schema: EntitySchema): SchemaField[] {
  return schema.fields.filter(f => 
    !f.isPrimaryKey || f.name !== 'id' // Usually hide ID column
  );
}

/**
 * Get form fields (editable + some timestamps for display)
 */
export function getFormFields(schema: EntitySchema): SchemaField[] {
  return getEditableFields(schema);
}

/**
 * Generate Zod schema for a field
 */
export function generateZodValidation(field: SchemaField): string {
  const baseSchema = (() => {
    switch (field.type) {
      case 'text':
      case 'fk':
        return 'z.string()';
      case 'integer':
        return 'z.number().int()';
      case 'real':
        return 'z.number()';
      case 'boolean':
        return 'z.boolean()';
      case 'enum':
        if (field.enumValues && field.enumValues.length > 0) {
          return `z.enum([${field.enumValues.map(v => `'${v}'`).join(', ')}])`;
        }
        return 'z.string()';
      default:
        return 'z.any()';
    }
  })();
  
  if (field.isRequired) {
    if (field.type === 'text') {
      return `${baseSchema}.min(1, 'Este campo es requerido')`;
    }
    return baseSchema;
  }
  
  return `${baseSchema}.optional()`;
}

// ============================================================================
// Main Export
// ============================================================================

export interface AnalyzerOptions {
  schemaDir?: string;
  schemaFile?: string;
}

/**
 * Main function to analyze an entity schema
 */
export function analyzeEntity(
  entityName: string, 
  options: AnalyzerOptions = {}
): EntitySchema {
  const schemaDir = options.schemaDir || 'src/db/schema';
  
  // Try to find the schema file
  const possiblePaths = [
    path.join(schemaDir, `${entityName}.ts`),
    path.join(schemaDir, 'index.ts'),
    path.join(schemaDir, `${toCamelCase(entityName)}.ts`),
  ];
  
  if (options.schemaFile) {
    possiblePaths.unshift(options.schemaFile);
  }
  
  for (const schemaPath of possiblePaths) {
    if (fs.existsSync(schemaPath)) {
      return analyzeSchema(schemaPath, entityName);
    }
  }
  
  throw new Error(`Could not find schema file for entity ${entityName}`);
}

export default {
  analyzeEntity,
  analyzeSchema,
  toPascalCase,
  toCamelCase,
  getTypeScriptType,
  getEditableFields,
  getVisibleFields,
  generateZodValidation,
};
